python render_video2.py \
    --python_app ../../apps/blur_one_stage_gray/blur_one_stage.py \
    --c_version ../../apps/blur_one_stage_gray/c/ \
    --input_frame_dir ../input_vids/fireworks_hd/frames/ \
    --output_dir ../input_vids/fireworks_hd/output_blur_one_stage_gray/ \
    --output_duration $1 \
    --output_fps 30 \
    --app_versions_to_use ours,numba,unpython,c \
    --no_input_img False \
    --app_title_str "Grayscale One-Stage Blur" \
    --use_grayscale_img_for_python True \
    --use_grayscale_img_for_c True