python render_video2.py \
    --python_app ../../apps/interpolate/interpolate_adjust_levels.py \
    --c_version ../../apps/interpolate/c/ \
    --input_frame_dir ../input_vids/fireworks_hd/frames/ \
    --output_dir ../input_vids/fireworks_hd/output_interpolate/ \
    --output_duration $1 \
    --output_fps 30 \
    --app_versions_to_use ours,numba,unpython,c \
    --no_input_img False \
    --app_title_str "Interpolate" \
    --use_4_channel_img_for_c True